### PR TITLE
[cases] updated claim filing flow  

### PR DESCRIPTION
**Pull request by arfamomin**
### Description
[//]: # "Required - Describe what's new in this PR in a few lines. A description and bullet points for specifics will suffice."

- new toggle between file a claim and opt out that switches potential flows for the user 
- once claim file indicated, new bar showing "claim filed" is added to top

### Screenshots
[//]: # 'Required for frontend changes, otherwise optional but strongly recommended. Add screenshots of expected behavior - GIFs if you're feeling fancy! Use the provided image template. Drag the desired image into the PR, then copy the link into the placeholder.'

## How to review
[//]: # 'Required - Describe the order in which to review files and what to expect when testing locally. Is there anything specifically you want feedback on? Should this be reviewed commit by commit, or all at once? What are some user flows to test? What are some edge cases to look out for?'

## Next steps
[//]: # "Optional - What's NOT in this PR, doesn't work yet, and/or still needs to be done. Note any temporary fixes in this PR that should be cleaned up later."

### Online sources
[//]: # 'Optional - copy links to any tutorials or documentation that was useful to you when working on this PR'

- Creating toggle https://uiverse.io/ErzenXz/weak-falcon-28, https://medium.com/@divvyatripaathi/building-toggle-switch-using-react-typescript-styled-components-38b45f054ea0

### Related PRs
[//]: # "Optional - related PRs you're waiting on/ PRs that will conflict, etc; if this is a refactor, feel free to add PRs that previously modified this code"

CC: @ronniebeggs

### CODE REVIEW

**Review by ronniebeggs — CHANGES_REQUESTED** [review]
I made a few refactoring changes that should hopefully clean up the eligibility logic. If you test out the claim filing flow, you'll notice that filing a claim will cause a "claim status" bar to show up. As of now I just reused a previously created component. Do you think you could create a new one according to this figma design? Or perhaps refactor the `CaseStatusBar` component so it can be used throughout the app? Let me know if this is doable or doesn't make sense.


Screen Shot 2024-04-30 at 6 42 55 PM

**Comment by arfamomin** [comment]
for positioning the texts inside the bar, i used `space-between` in my commits but it looks a bit weird on my larger phone. here's what it looks with `space-around`  but the look changed slightly so lmk if you want to change it.

**Comment by arfamomin** [comment]
I also didn’t refactor CaseStatusBar and made a new component instead b/c it would require changing the text styling (since it’s not the same as what’s pulled from getStatusColor). But whenever you review it and think it might be better I also have the code for it refactored instead where I override the styling.

**Comment by ronniebeggs** [comment]
> I also didn’t refactor CaseStatusBar and made a new component instead b/c it would require changing the text styling (since it’s not the same as what’s pulled from getStatusColor). But whenever you review it and think it might be better I also have the code for it refactored instead where I override the styling.

It's honestly probably fine to create a new component. Let's just run with this.

**Comment by ronniebeggs** [comment]
> for positioning the texts inside the bar, i used `space-between` in my commits but it looks a bit weird on my larger phone. here's what it looks with `space-around` but the look changed slightly so lmk if you want to change it.
> 
> 

I worry that it might not look great on every screen. Space around looks a little awkward on my screen so I think it's fine how it is for now.

**Pull request merged**
